// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Ensure HTTPS URLs
const ensureHTTPS = (url: string): string => {
  if (!url) return url;
  if (typeof window !== 'undefined' && window.location.protocol === 'https:') {
    return url.replace(/^http:/, 'https:');
  }
  return url;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  ensureHTTPS(SUPABASE_URL), 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'X-Client-Info': 'rocket-launch-hosting'
      }
    }
  }
);